FROM node:20-alpine

# Enable Corepack to support Yarn
RUN corepack enable

WORKDIR /app

COPY . .

RUN yarn install


# Build the shared package
WORKDIR /app/packages/shared
RUN yarn build


EXPOSE 3000

# Set working directory and run web dev command
WORKDIR /app/apps/web
CMD ["yarn", "dev"] 