FROM node:20-alpine

# Using npm as package manager

WORKDIR /app

COPY . .

RUN npm install


# Build the shared package
WORKDIR /app/packages/shared
RUN npm run build


EXPOSE 3000

# Set working directory and run web dev command
WORKDIR /app/apps/web
CMD ["npm", "run", "dev"] 