version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "5002:5001"
    environment:
      - NODE_ENV=development
      - PORT=5001
      - MONGODB_CONNECTION_STRING=mongodb+srv://tynoukus:Tyno4real@foodapp.xvp0l.mongodb.net/?retryWrites=true&w=majority&appName=FoodApp
      - JWT_SECRET=your-super-secret-jwt-key-for-development-only
      - JWT_REFRESH_SECRET=your-super-secret-jwt-refresh-key-for-development-only
    depends_on:
      - mongo

  # Web App
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BACKEND_URL=http://backend:5001/api
      - NEXT_PUBLIC_BACKEND_URL_PLAIN=http://backend:5001
      - NEXTAUTH_SECRET=your-super-secret-nextauth-key-for-development-only
      - NEXTAUTH_URL=http://localhost:3001
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app/apps/web
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - backend

  # MongoDB
  mongo:
    image: mongo:5
    ports:
      - "27018:27017"
    command: mongod --bind_ip_all

volumes:
  mongo_data: 