# version: '3.8'

services:
  # Backend API (Development)
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile.dev
    ports:
      - "5002:5001"
    environment:
      - NODE_ENV=development
      - PORT=5001
      - MONGODB_CONNECTION_STRING=mongodb+srv://tynoukus:Tyno4real@foodapp.xvp0l.mongodb.net/?retryWrites=true&w=majority&appName=FoodApp
      - JWT_SECRET=your-super-secret-jwt-key-for-development-only
      - JWT_REFRESH_SECRET=your-super-secret-jwt-refresh-key-for-development-only
      - ALLOWED_ORIGINS=http://localhost:3001,http://localhost:3000
      - MEDIA_SERVICE_URL=http://localhost:3002/api/v1
      - MEDIA_SERVICE_TIMEOUT=30000


  # Web App (Development)
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:5002
      - BACKEND_URL_SERVER=http://backend:5001
      - NEXTAUTH_SECRET=your-super-secret-nextauth-key-for-development-only
      - NEXTAUTH_URL=http://localhost:3001
      - BACKEND_URL_CLIENT=http://localhost:5002
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend

  # Media Service (Development)
  media-service:
    build:
      context: .
      dockerfile: apps/media-service/Dockerfile.dev
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - MONGODB_CONNECTION_STRING=mongodb+srv://tynoukus:Tyno4real@foodapp.xvp0l.mongodb.net/?retryWrites=true&w=majority&appName=FoodApp
      - CLOUDINARY_CLOUD_NAME=your_cloud_name
      - CLOUDINARY_API_KEY=your_api_key
      - CLOUDINARY_API_SECRET=your_api_secret
      - ALLOWED_ORIGINS=http://localhost:3001,http://localhost:3000
    volumes:
      - ./apps/media-service:/app
      - /app/node_modules
    depends_on:
      - backend

 