import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { auth } from "@/auth";
import Provider from "@/providers/Provider";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bite Scout",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en" className={montserrat.className}>
      <body>
        <Provider session={session}>
          <ToastContainer />
          <main className="">{children}</main>
        </Provider>
      </body>
    </html>
  );
}
