const mongoose = require("mongoose");
const { Schema, model } = mongoose;

const foodCatalogueSchema = new Schema({
  foodName: {
    type: String,
    required: true,
    trim: true,
  },
  ingredents: {
    type: [String],
    required: true,
  },
  cuisineTypes: {
    type: String,
    required: true,
    enum: [
      "American",
      "Italian",
      "Mexican",
      "Chinese",
      "Japanese",
      "Indian",
      "Thai",
      "French",
      "German",
      "Spanish",
      "Russian",
      "Turkish",
      "Vietnamese",
      "Greek",
      "Indonesian",
      "Korean",
      "Lebanese",
      "Malaysian",
      "Mexican",
      "Nepali",
      "Pakistani",
      "Persian",
      "Nigerian",
      "Romanian",
      "Scottish",
      "Taiwanese",
      "Vietnamese",
      "Welsh",
      "Yemenite",
      "Yugoslavian",
      "Zambian",
    ],
    allergens: {
      type: String,
      required: true,
      enum: [
        "Gluten",
        "Dairy",
        "Egg",
        "Crustaceans",
        "Celery",
        "Fish",
        "Lupin",
        "Milk",
        "Molluscs",
        "Mustard",
        "Peanuts",
        "Sesame",
        "Soybeans",
        "Sulphur dioxide",
        "Sulphites",
      ],
    },
    mealComponent: {
      type: String,
      required: true,
      enum: [
        "Appetizer",
        "Main Course",
        "Dessert",
        "Beverage",
        "Salad",
        "Side Dish",
      ],
    },
    price: {
      type: Number,
      required: true,
    },
    images: {
      type: [String],
      required: true,
    },
  },
});
