openapi: "3.0.0"
info:
  version: 1.0.0
  title: "BiteScout API"
  description: "API documentation for BiteScout"
servers:
  - url: http://localhost:3000/api
paths:
  /auth/register:
    summary: Register a user
    description: Creates a  new user account with Provided credentials
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - firstName
                - lastName
                - email
                - password
              properties:
                firstName:
                  type: string
                  example: Anthony
                lastName:
                  type: string
                  example: Ukutegbe
                email:
                  type: string
                  format: email
                  example: anthony@test.com
                password:
                  type: string
                  format: password
                  example: strongPassword123

      responses:
        201:
          description: Successfully registered user
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Registration successful
                  user:
                    type: object
                    properties:
                      name:
                        type: string
                        example: Anthony Ukutegbe
                      email:
                        type: string
                        format: email
                        example: anthony@test.com
                      userType:
                        type: object
                        properties:
                          name:
                            type: string
                            example: user
                          level:
                            type: number
                            example: 1
                          description:
                            type: string
                            example: an ordinary user with restaurnat access
        400:
          description: Missing required field or invalid user type
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Missing required field or user type not found
        409:
          description: Conflict – User already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User already exists
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                userCreationError:
                  summary: Error creating User
                  value:
                    message: Error creating user
                    error: Database conection failed
  /auth/login:
    summary: Authenticate a user
    description: Authenticate a user and return accesss and refresh token
    get:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: anthony@test.com
                password:
                  type: string
                  format: password
                  example: strongPassword123
      responses:
        200:
          description: Login Successfull
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Login successful
                  user:
                    type: object
                    $ref: "#/components/schemas/User"
                  accessToken:
                    type: string
                    example: -access token here-
                  refreshToken:
                    type: string
                    example: -refresh token here-
                  expiresIn:
                    type: integer
                    format: int64
                    description: "Expiration time as a Unix timestamp in milliseconds"
                    example: 1713649200000
        400:
          description: Missing required field or invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Missing required fields
              examples:
                missingFields:
                  summary: Missing required fields
                  value:
                    message: Missing required fields
                userNotFound:
                  summary: User not found
                  value:
                    message: User not found
                invalidCredentials:
                  summary: Invalid credentials
                  value:
                    message: Invalid credentials
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                LoginError:
                  summary: Error Logging in
                  value:
                    message: Error Logging In
                    Error: Database connection failed
  /auth/refresh:
    summary: Refresh authenticatio token
    description: Refreshes the authentication token with the provided refresh token
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - refreshToken
              properties:
                refreshToken:
                  type: string
                  example: -refresh token here-

      responses:
        200:
          description: Token refresh successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Refresh Token Successfull
                  accessToken:
                    type: string
                    example: -new access token here-
                  refreshToken:
                    type: string
                    example: -new refresh token here-
                  expiresIn:
                    type: integer
                    format: int64
                    description: Expiration time as a Unix timestamp in milliseconds
                    example: 1713649200000
        400:
          description: Refresh token not found or Invalid Token
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Refresh token not found
              examples:
                missingToken:
                  summary: Missing token
                  value:
                    message: Refresh token not found
                invalidToken:
                  summary: Invalid refresh token
                  value:
                    message: Invalid refresh token
        401:
          description: Internal Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid Refresh Token Request

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: A human-readable description of the error.
          example: An unexpected error has occured
        error:
          type: string
          description: Detailed error message.
          example: "Database connection failed"

    User:
      type: object
      properties:
        username:
          type: string
          example: anthony_ukutegbe
        phone:
          type: string
          example: "+2347012345678"
        name:
          type: string
          example: Anthony Ukutegbe
        email:
          type: string
          format: email
          example: anthony@test.com
        hometown:
          type: string
          example: Lagos
        currentCity:
          type: string
          example: Abuja
        country:
          type: string
          example: Nigeria
        imageUrl:
          type: string
          example: https://example.com/avatar.jpg
        address:
          type: string
          example: "123, Some Street, City"
        password:
          type: string
          format: password
          example: strongPassword123
        isVerified:
          type: boolean
          example: false
        userType:
          type: string
          example: userTypeId
        createdAt:
          type: string
          format: date-time
          example: "2025-04-20T15:30:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2025-04-20T15:30:00Z"
      required:
        - name
        - email
        - password
        - userType
    Allergen:
      type: object
      properties:
        name:
          type: string
          example: egg
        description:
          type: string
          example: allergic reaction to eggs and food that has egg content
    Course:
      type: object
      properties:
        name:
          type: string
          example: main
        description:
          type: string
          example: Main course in a meal
    Cuisine:
      type: object
      properties:
        name:
          type: string
          example: Nigerian
        description:
          type: string
          example: A Type of meal based on region of origin
    BusinessHour:
      type: object
      properties:
        day:
          type: string
          enum:
            - Monday
            - Tuesday
            - Wednesday
            - Thursday
            - Friday
            - Saturday
            - Sunday
        open:
          type: string
          pattern: "^([01]\\d|2[0-3]):([0-5]\\d)$"
          description: "Opening time in HH:mm format"
        close:
          type: string
          pattern: "^([01]\\d|2[0-3]):([0-5]\\d)$"
          description: "Closing time in HH:mm format"
        closed:
          type: boolean
          default: false
          description: "Indicates if the restaurant is closed on this day"
    Restaurant:
      type: object
      required:
        - ownerId
        - name
      properties:
        ownerId:
          type: string
          description: "Unique identifier for the restaurant owner"
        name:
          type: string
          description: "Name of the restaurant"
        logo:
          type: string
          format: uri
          description: "URL to the restaurant's logo image"
        description:
          type: string
          description: "Brief description of the restaurant"
        cuisine:
          type: array
          items:
            type: string
          description: "List of cuisines offered by the restaurant"
        priceRange:
          type: string
          enum:
            - "$"
            - "$$"
            - "$$$"
            - "$$$$"
          description: "Price range of the restaurant"
        address:
          type: string
          description: "Physical address of the restaurant"
        phone:
          type: string
          pattern: "^\\+?[\\d\\s-()]+$"
          description: "Contact phone number"
        email:
          type: string
          format: email
          description: "Contact email address"
        website:
          type: string
          format: uri
          description: "Website URL of the restaurant"
        businessHours:
          type: array
          items:
            $ref: "#/components/schemas/BusinessHour"
          description: "Operating hours for each day of the week"
        features:
          type: array
          items:
            type: string
            enum:
              - "Outdoor seating"
              - "Dining area"
              - "Take-out"
              - "Delivery"
              - "Catering"
              - "Wifi"
              - "Parking"
          description: "List of features available at the restaurant"
        gallery:
          type: array
          items:
            type: string
            format: uri
          description: "URLs to images in the restaurant's gallery"
        meta:
          type: object
          additionalProperties: true
          description: "Additional metadata associated with the restaurant"

    Price:
      type: object
      required:
        - amount
        - currency
      properties:
        amount:
          type: number
          description: "The price amount"
          example: 25.99
        currency:
          type: string
          enum:
            - USD
            - EUR
            - GBP
            - CAD
            - AUD
            - JPY
            - CNY
            - KRW
            - MYR
            - TWD
            - VND
            - THB
            - ZAR
          description: "Currency type"
          example: "USD"

    FoodCatalogue:
      type: object
      required:
        - name
        - ingredients
        - cuisineType
        - course
        - price
        - images
        - restaurant
      properties:
        name:
          type: string
          description: "The name of the food item"
          example: "Spaghetti Bolognese"
        ingredients:
          type: array
          items:
            type: string
          description: "List of ingredients used in the food item"
          example:
            - "Spaghetti"
            - "Ground beef"
            - "Tomato sauce"
        cuisineType:
          type: string
          description: "Cuisine type the food belongs to"
          example: "Italian"
        allergens:
          type: array
          items:
            type: string
          description: "List of allergens associated with the food"
          example:
            - "Gluten"
            - "Dairy"
        course:
          type: string
          description: "Course type the food belongs to (e.g., starter, main)"
          example: "Main course"
        price:
          $ref: "#/components/schemas/Price"
          description: "Price details for the food item"
        images:
          type: array
          items:
            type: string
            format: uri
          description: "List of image URLs for the food item"
          example:
            - "https://example.com/images/spaghetti-bolognese-1.jpg"
            - "https://example.com/images/spaghetti-bolognese-2.jpg"
        restaurant:
          type: string
          description: "ID of the restaurant offering the food item"
          example: "restaurant12345"
