FROM node:20-alpine

# Enable Corepack to support Yarn
RUN corepack enable

WORKDIR /app

COPY package*.json turbo.json ./
COPY packages/shared/package*.json ./packages/shared/
COPY apps/backend/package*.json ./apps/backend/

RUN yarn install

COPY . .

# Backend-specific environment variables
ENV NODE_ENV=development
ENV PORT=5001

EXPOSE 5001

# Run backend dev command
CMD ["yarn", "dev"] 