import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { ReduxProvider } from "@/components/ReduxProvider";
import { UserProvider } from "@auth0/nextjs-auth0/client";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bite Scout",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>
        <UserProvider>
          <ReduxProvider>
            <ToastContainer />
            <main className="">{children}</main>
          </ReduxProvider>
        </UserProvider>
      </body>
    </html>
  );
}
