name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
      
    - name: test docker
      run: cat Dockerfile.prod
    - name: Build the Docker image
      run: docker build . --file Dockerfile.prod --tag my-image-name:$(date +%s) --no-cache
